services:
  - type: web
    name: proteogenomix-app
    env: node
    plan: free
    buildCommand: |
  cd client && npm install && npm run build && cd ..
  cd server && npm install && \
  esbuild index.ts --platform=node --packages=external --bundle --format=cjs --outfile=../dist/server.js && cd ..
    startCommand: node dist/server.js
    envVars:
      - key: SUPABASE_URL
        value: your-supabase-url
      - key: SUPABASE_ANON_KEY
        value: your-anon-key
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - client/
        - server/